# Generated by Django 3.2.8 on 2021-10-29 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sell_house', '0002_house'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=200, null=True)),
                ('House', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sell_house.house')),
                ('User', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sell_house.user')),
            ],
        ),
    ]
